services:
  - type: web
    name: clothing-store
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn clothing_store.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: clothing_store.settings
      - key: PYTHON_VERSION
        value: 3.10
